// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFriendReq = "friend_req"

// FriendReq mapped from table <friend_req>
type FriendReq struct {
	UID      int64     `gorm:"column:uid;not null" json:"uid"`
	FriendID int64     `gorm:"column:friend_id;not null" json:"friend_id"`
	Msg      string    `gorm:"column:msg" json:"msg"`
	IsAgree  int32     `gorm:"column:is_agree;comment:-1：拒绝 0：未处理 1：同意" json:"is_agree"` // -1：拒绝 0：未处理 1：同意
	CreatAt  time.Time `gorm:"column:creat_at;default:CURRENT_TIMESTAMP(3)" json:"creat_at"`
	UpdateAt time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP(3)" json:"update_at"`
}

// TableName FriendReq's table name
func (*FriendReq) TableName() string {
	return TableNameFriendReq
}
