// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFriend = "friend"

// Friend mapped from table <friend>
type Friend struct {
	ID       int64     `gorm:"column:id;primaryKey" json:"id"`
	FriendID int64     `gorm:"column:friend_id;not null" json:"friend_id"`
	NickName string    `gorm:"column:nick_name;comment:好友备注名" json:"nick_name"`   // 好友备注名
	Status   int32     `gorm:"column:status;comment:0.正常1.黑名单2.删除" json:"status"` // 0.正常1.黑名单2.删除
	CreateAt time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP(3)" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP(3)" json:"update_at"`
	DeleteAt time.Time `gorm:"column:delete_at" json:"delete_at"`
}

// TableName Friend's table name
func (*Friend) TableName() string {
	return TableNameFriend
}
