// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID             int64     `gorm:"column:id;primaryKey" json:"id"`
	RoomID         int64     `gorm:"column:room_id;not null" json:"room_id"`
	From           int64     `gorm:"column:from;not null" json:"from"`
	To             int64     `gorm:"column:to;not null" json:"to"`
	Content        string    `gorm:"column:content;not null;comment:消息内容" json:"content"`                                  // 消息内容
	MessageType    int32     `gorm:"column:message_type;comment:消息类型{text, picture or other}:{0，1，2）" json:"message_type"` // 消息类型{text, picture or other}:{0，1，2）
	AdditionalInfo string    `gorm:"column:additional_info;comment:额外信息" json:"additional_info"`                           // 额外信息
	Status         int32     `gorm:"column:status;default:1;comment:0.已撤回1.正常消息" json:"status"`                            // 0.已撤回1.正常消息
	SendAt         time.Time `gorm:"column:send_at;default:CURRENT_TIMESTAMP(3)" json:"send_at"`
	UpdateAt       time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP(3)" json:"update_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
