// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoom = "room"

// Room mapped from table <room>
type Room struct {
	RoomID   int64     `gorm:"column:room_id;not null" json:"room_id"`
	UID      int64     `gorm:"column:uid;not null" json:"uid"`
	Type     int32     `gorm:"column:type;comment:0：私聊  1：群聊" json:"type"`                // 0：私聊  1：群聊
	Nickname string    `gorm:"column:nickname;comment:聊天室内昵称" json:"nickname"`            // 聊天室内昵称
	Role     int32     `gorm:"column:role;comment:-1：已退出 0：普通成员  1：管理员 2：群主" json:"role"` // -1：已退出 0：普通成员  1：管理员 2：群主
	Ban      int32     `gorm:"column:ban;comment:0：正常发言 1：被禁言" json:"ban"`                // 0：正常发言 1：被禁言
	JoinAt   time.Time `gorm:"column:join_at;default:CURRENT_TIMESTAMP(3)" json:"join_at"`
	UpdateAt time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP(3)" json:"update_at"`
	ExitAt   time.Time `gorm:"column:exit_at" json:"exit_at"`
}

// TableName Room's table name
func (*Room) TableName() string {
	return TableNameRoom
}
