system:
  host: 0.0.0.0:8080
  env: info
  datacenterID: 0
  workerID: 0

mysql:
  host: 192.168.175.136:3306
  user: root
  passwd: 123123
  database: im
  log_level: dev

logger:
  level: warn
  prefix: "[SYS]"
  director: log
  show_line: true
  log_in_console: true

redis:
  host: 192.168.175.136:6379
  passwd: 123456
  db: 0

rocketmq:
  host: 192.168.175.136:9876
  group: im

jwt:
 valid_time: 24 # hours